// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmgzipjmudsfxyrqbvih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tZ3ppcGptdWRzZnh5cnFidmloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTM2NTUsImV4cCI6MjA3MDAyOTY1NX0.V2cJw51QyO_WrcaXiwcKSc3daDTtLGleG8fSYTNWScM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});